# -*- coding: utf-8 -*-
"""Copie de HACKATHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLYR4z2ruCTTIb_6dBtk8Acb2nGxWZiF
"""

import pandas as pd
import numpy as np
import random

# GÉNÉRATION DE BASE
categories = ['Tourisme', 'Culture', 'Tech', 'fitness', 'music', 'danse']

actions_par_categorie = {
    'Tourisme': ['clic_article_voyage', 'recherche_hotel', 'vue_video_plage'],
    'Culture': ['lecture_article_histoire', 'clic_expo_musee', 'vue_docu_art'],
    'Tech': ['vue_tuto_python', 'telechargement_app', 'clic_actu_ia'],
    'fitness': ['achat_produit_sport', 'vue_tuto_exercice', 'inscription_salle_sport'],
    'music': ['ecoute_chanson', 'achat_album', 'recherche_artiste'],
    'danse': ['vue_video_danse', 'inscription_cours_danse', 'partage_performance']
}

donnee = []

for i in range(100):
    interet = random.choice(categories)
    logs = random.choices(actions_par_categorie[interet], k=random.randint(2, 3))

    donnee.append({
        'NOM': f"User_{i}",
        'AGE': random.randint(15, 65),
        'Centre_interet': interet,
        'activity_log': logs
    })

#  IMPORTANT : création de df (ligne clé)
df = pd.DataFrame(donnee)

# --- 2. INJECTION DE BUGS (dataset sale) ---

# valeurs manquantes
df.loc[df.sample(frac=0.05).index, 'AGE'] = np.nan
df.loc[df.sample(frac=0.05).index, 'Centre_interet'] = np.nan

# valeurs aberrantes
df.loc[2, 'AGE'] = -10
df.loc[15, 'AGE'] = 250

# doublons
doublons = df.head(3)
df = pd.concat([df, doublons], ignore_index=True)

# mélange
df = df.sample(frac=1).reset_index(drop=True)

# --- 3. CHECK FINAL ---
print("Dataset prêt ")
print(df.shape)
print(df.head(10))

#Exploration initiale
print(df.shape)
print(df.dtypes)
print(df['AGE'].describe())

#Suppression des doublons

# Convert the 'activity_log' column to a hashable type (string) to avoid TypeError
df['activity_log'] = df['activity_log'].apply(lambda x: str(x) if isinstance(x, list) else x)

nb_doublons = df.duplicated().sum()
print(f"Doublons : {nb_doublons}")

df = df.drop_duplicates().reset_index(drop=True)
print(f"Shape après nettoyage : {df.shape}")

#Valeurs manquantes (NaN)
print(df.isnull().sum())

mediane_age = df['AGE'].median()
df['AGE'] = df['AGE'].fillna(mediane_age)

mode_interet = df['Centre_interet'].mode()[0]
df['Centre_interet'] = df['Centre_interet'].fillna(mode_interet)

print("NaN restants :", df.isnull().sum().sum())

#Valeurs aberrantes (Outliers)

masque_outlier = (df['AGE'] < 15) | (df['AGE'] > 65)
print(df[masque_outlier][['NOM', 'AGE']])

mediane = df.loc[~masque_outlier, 'AGE'].median()
df.loc[masque_outlier, 'AGE'] = mediane

# Alternative : df['AGE'] = df['AGE'].clip(15, 65)

#Nettoyage des catégories
print(df['Centre_interet'].unique())  # repérer les espaces

df['Centre_interet'] = (
    df['Centre_interet']
    .str.strip()
    .str.capitalize()
)

print(df['Centre_interet'].value_counts())

#Typage & Encodage
from sklearn.preprocessing import LabelEncoder

df['AGE'] = df['AGE'].astype(int)

le = LabelEncoder()
df['Centre_interet_enc'] = le.fit_transform(df['Centre_interet'])

df['nb_actions'] = df['activity_log'].apply(len)

print(df.dtypes)

#Export final
print(f"Shape final : {df.shape}")
print(df.describe())

df.to_csv('dataset_propre.csv', index=False)
print("dataset_propre.csv sauvegardé !")